remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
relative_links:
  enabled: true
  collections: true

title: My title here
description: Text in small font under the title
author: I don't know where the author name goes
include:
  - research_summary.md
