remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
relative_links:
  enabled: true
  collections: true

title: Managing Knowledge Resources in Agile Software Development
description: Raquel Ouriques - Doctoral thesis content
author: Raquel Ouriques
include:
  - README.md
